---
- name: Restart prometheus
  listen: "restart prometheus"
  become: true
  ansible.builtin.command: "docker compose down -v && docker compose up -d"
  args:
    chdir: "{{ prometheus_compose_dir }}"

- name: Reload prometheus
  listen: "reload prometheus"
  become: true
  ansible.builtin.command: "curl -s -XPOST localhost:9090/-/reload"